// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    BookCard: typeof import('./src/components/BookCard.vue')['default']
    CtaButton: typeof import('./src/components/CtaButton.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TawHeader: typeof import('./src/components/TawHeader.vue')['default']
    TestimonialCard: typeof import('./src/components/TestimonialCard.vue')['default']
    TestimonialRating: typeof import('./src/components/TestimonialRating.vue')['default']
    TestimonialsSection: typeof import('./src/components/TestimonialsSection.vue')['default']
    Trending: typeof import('./src/components/Trending.vue')['default']
  }
}
